name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Update submodules"]
    branches: [master]
    types: 
      - completed
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false 
          submodules: true

      - name: Install and Build 🔧
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.417'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: |
          dotnet --version
          dotnet --list-runtimes
          bash ./install.sh
          bash ./build.sh

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build

